language: python
python:
  - 2.7
  - 3.5

matrix:
  include:
    - python: 2.7
      install:
        - pip install flake8
        - pip install isort
      script:
        - flake8 znclogs/**/*.py
        - isort -c znclogs/**/*.py

install:
  - pip install pytest-cov

script: py.test --cov=znclogs znclogs/

after_success:
  - pip install coveralls
  - coveralls
